package com.truekenyan.cocktail.utils

object Commons {
    const val FIRST_TIME_LAUNCH = "cocktail-first-time-launch"
    const val HAS_LAUNCHED = "has-launched"
    const val DRINK_ID = "drink-id"
    const val DRINKS = "drinks"
    const val URL_ALCOHOLIC = "https://www.thecocktaildb.com/api/json/v1/1/filter.php?a=Alcoholic"
    const val URL_NON_ALCOHOLIC = "https://www.thecocktaildb.com/api/json/v1/1/filter.php?a=Non_Alcoholic"
    const val INGREDIENT_SEARCH = "https://www.thecocktaildb.com/api/json/v1/1/filter.php?i="
    const val NAME_SEARCH = "https://www.thecocktaildb.com/api/json/v1/1/search.php?s="
    const val COCKTAIL = "https://www.thecocktaildb.com/api/json/v1/1/lookup.php?i="
    const val URL_RANDOM = "https://www.thecocktaildb.com/api/json/v1/1/random.php"
    const val ALCOHOLIC = "Alcoholic"
    const val NON_ALCOHOLIC = "Non Alcoholic"
    const val COCKTAILS = "Cocktails"
    const val SEARCH = "Search"
    const val FAVORITES = "Favorites"
    const val INFO = "Info"
    const val DRINK_NAME = "drinkName"
    const val DOWNLOAD_URL = "https://goo.gl/8U839A" //TODO update URL
    const val FAV_ID = "favId"
    const val ORDER = "Order"
    const val ASCENDING = "Ascending"
    const val DESCENDING = "Descending"
    const val RANDOM = "Random"
    const val USE_NAME = "use-name"
    const val HOME = "Home"
    const val CACHE_DIR = "/Cocktail/"
    const val CACHE_FILE_NAME = ""
}